version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - flask-postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file: .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis


  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env


volumes:
  flask-postgres-volume:
    driver: local
  redis_data:
    driver: local

