# Generated by Django 5.1.3 on 2024-11-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('send_date', models.DateTimeField()),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField()),
                ('attachments', models.JSONField()),
                ('unique_hash', models.CharField(max_length=255, null=True, unique=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_integration.emailaccount')),
            ],
        ),
    ]
